# External gems - updated to plugins in jekyll v3.6
plugins:

   - jekyll-seo-tag
   - jekyll-sitemap

title: Fit 2 Study
email: "support@eyedivision.com"
description: >- # this means to ignore newlines until "baseurl:"
  The ‘Fit to Study‘ project is a randomised controlled study to test the impact on academic performance (as well as fitness, wellbeing and cognitive function) of a teacher training intervention designed to try to optimise the content of PE for brain and cognitive function during secondary school (Year 8) Physical Education (PE) lessons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.fit-to-study.org" # the base hostname & protocol for your site, e.g. http://example.com
asset_url: "/assets/"


# Build settings
markdown: kramdown

# https://docs.cloudcannon.com/editing/options/
_options:
  _text:            # text =
    link: true
    bold: true
    italic: true
    removeformat: true
  _block:           # block = editable blocks within pages
    link: true
    bold: true
    italic: true
    removeformat: true
    left: align-left
    center: center-this-text
    right: align-right
    justify: full-width-text
    undo: true
    redo: true
    format: p h2 h3 h4 h5 h6 div
    numberedlist: true
    bulletedlist: true
    blockquote: true
    superscript: true
    image: true
    styles: /css/editor.scss
  content:
    link: true
    bold: true
    italic: true
    superscript: true
    removeformat: true
    left: align-left
    center: center-this-text
    right: align-right
    justify: full-width-text
    undo: true
    redo: true
    format: p h2 h3 h4 h5 h6 div
    numberedlist: true
    bulletedlist: true
    blockquote: true
    image: true
    styles: /css/editor.scss